sudo: false
language: python
python:
  - "2.7"
install:
  - pip install tox-travis
  - pip install lambda-uploader
  - pip install coveralls
script: tox
after_success:
  - coveralls
  - lambda-uploader
